name: Gannt Issue Overview
description: Use the smaller tasks for me to keep track of.
title: "[Micro]: "
labels: ["Type: Gantt"]
assignees:
  - makamadams2008-wq
body:
  - type: markdown
    attributes:
      value: |
        # Micro Issue Overview 

  - type: input
    id: startDate
    attributes:
      label: Start Date
      value: "GanttStart: 2026-"
    validations:
      required: true

  - type: input
    id: dueDate
    attributes:
      label: Due Date
      value: "GanttDue: 2026-"

    validations:
      required: true
      
  - type: textarea
    id: keyTasks
    attributes:
      label: Key Tasks
      description: What is the pourpouse what are the goals.
    validations:
      required: true

    - type: textarea
    id: relflection
    attributes:
      label: Reflection
      description: How did this sprint go, what where the chananges, what did you learn.

  - type: checkboxes
    id: stakeholders
    attributes:
      label: Relevant Stakeholders
      options:
        - label: MR Harding 
        - label: Mrs Hone 
        - label: Ms Murffy
        - label: Bruce Trevarthen
        - label: Other 
    validations:
      required: true
      
  - type: checkboxes
    id: subject
    attributes:
      label: Allocated Subject
      options:
        - label: HTK
        - label: DVC
        - label: DIT
        - label: Home
        - label: Other
    validations:
      required: true
      
  - type: textarea
    id: notes
    attributes:
      label: Other Notes
      description: References, links, or extra details.
GanttFollows: {{ follows }}
